language: python
env:
    matrix:
        - PYTHON=3.7 NUMPY=1.15 SCIPY=1.1 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.15 SCIPY=1.0 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.15 SCIPY=0.19 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.14 SCIPY=1.1 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.14 SCIPY=1.0 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.14 SCIPY=0.19 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.13 SCIPY=1.1 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.13 SCIPY=1.0 SUITESPARSE=5.2
        - PYTHON=3.7 NUMPY=1.13 SCIPY=0.19 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.15 SCIPY=1.1 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.15 SCIPY=1.0 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.15 SCIPY=0.19 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.14 SCIPY=1.1 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.14 SCIPY=1.0 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.14 SCIPY=0.19 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.13 SCIPY=1.1 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.13 SCIPY=1.0 SUITESPARSE=5.2
        - PYTHON=3.6 NUMPY=1.13 SCIPY=0.19 SUITESPARSE=5.2
install:
    # install conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    # create test environment
    - conda create -q -n test-environment
    - conda activate test-environment
    # install needed packages
    - conda install -q python=$PYTHON
    - conda install -q numpy=$NUMPY
    - conda install -q scipy=$SCIPY
    - conda install -q suitesparse=$SUITESPARSE
    - conda install -q nose
    - conda list
    # install this package
    - python setup.py build_ext --inplace
script:
    - nosetests -sv sksparse
